name       : haskell-persistent
version    : 2.6.1
release    : 1
source     :
    - http://hackage.haskell.org/package/persistent-2.6.1/persistent-2.6.1.tar.gz : c79e0f6e7b727dcae0c7c541f1d47eb8fb0b9e9c55d2478a476a4aca8e405f7e
license    : BSD-3-Clause
component  : programming.haskell
summary    : Type-safe, data serialization.
description: |
    Type-safe, data serialization.
builddeps  :
    - haskell-aeson
    - haskell-blaze-html
    - haskell-cabal-install
    - haskell-http-api-data
    - haskell-monad-logger
    - haskell-path-pieces
    - haskell-resource-pool
    - haskell-silently
    - haskell-tagged
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
