name       : haskell-persistent
version    : 2.9.2
release    : 3
source     :
    - https://hackage.haskell.org/package/persistent-2.9.2/persistent-2.9.2.tar.gz : 497e5d2c96aaa370f147ece995a798d1ea217e35996f908d42681f41ec1c4af3
license    : MIT
component  : programming.haskell
summary    : Type-safe, data serialization.
description: |
    Type-safe, data serialization.
builddeps  :
    - haskell-aeson-devel
    - haskell-base64-bytestring-devel
    - haskell-blaze-html-devel
    - haskell-cabal-install
    - haskell-http-api-data-devel
    - haskell-monad-logger-devel
    - haskell-path-pieces-devel
    - haskell-resource-pool-devel
    - haskell-silently-devel
    - haskell-void-devel
rundeps    :
    - devel:
        - haskell-aeson-devel
        - haskell-base64-bytestring-devel
        - haskell-blaze-html-devel
        - haskell-http-api-data-devel
        - haskell-monad-logger-devel
        - haskell-path-pieces-devel
        - haskell-resource-pool-devel
        - haskell-silently-devel
        - haskell-void-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
