name       : haskell-persistent
version    : 2.8.2
release    : 2
source     :
    - http://hackage.haskell.org/package/persistent-2.8.2/persistent-2.8.2.tar.gz : 696bb279259e307778dc7fbd49565c48a66429f14e793a41a13cfae0968c1ec0
license    : BSD-3-Clause
component  : programming.haskell
summary    : Type-safe, data serialization.
description: |
    Type-safe, data serialization.
builddeps  :
    - haskell-aeson
    - haskell-base64-bytestring
    - haskell-blaze-html
    - haskell-cabal-install
    - haskell-http-api-data
    - haskell-monad-logger
    - haskell-path-pieces
    - haskell-resource-pool
    - haskell-silently
    - haskell-src-meta
    - haskell-tagged
    - haskell-void
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
